### ISSUE TITLE
Error while building even after updating keystore password on Windows

### ISSUE THREAD

**Issue by ajaybarvey** [athingunique/Drive-Database-Sync#4]
Hello,
I tried to build the code and I get following error even though I have updated build.gradle  with correct keystore password. (Your code has password in gradle.properties and not in radle.properties.)

Error-
Error:(13, 1) A problem occurred evaluating project ':example'.

> You should define KEYSTORE_PASSWORD and KEY_PASSWORD in gradle.properties.

---

My build.gradle is as follows-

apply plugin: 'com.android.application'

android {
    signingConfigs {
        releaseKeys {
            try {
                keyAlias 'android'
                keyPassword android
                storeFile file('C:\keystore.jks')
                storePassword android
            }
            catch (ignored) {
                throw new InvalidUserDataException("You should define KEYSTORE_PASSWORD and KEY_PASSWORD in gradle.properties.")
            }
        }
    }
    compileSdkVersion 22
    buildToolsVersion "22.0.1"
    defaultConfig {
        applicationId "com.github.athingunique.ddbs_ex"
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 2
        versionName "0.0.2"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.releaseKeys
        }
        debug {
            signingConfig signingConfigs.releaseKeys
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.jakewharton:butterknife:6.1.0'

```
// Include this line to pull from the release repo
// compile 'com.github.athingunique:ddbs:0.0.4'
compile project(':ddbs')
```

}

**Comment by rbtr** [comment]
> Your code has password in gradle.properties and not in radle.properties

Don't know what you mean...put your keystore info in the gradle.properties, NOT the build.gradle.
This is not an issue with the library.
