### ISSUE TITLE
Getting error: Error:Execution failed for task ':example:processDebugResources'. > Error: more than one library with package name 'com.github.athingunique.ddbs'

### ISSUE THREAD

**Issue by ajaybarvey** [athingunique/Drive-Database-Sync#5]
While compiling I am getting the following error:
 Error:Execution failed for task ':example:processDebugResources'. > Error: more than one library with package name 'com.github.athingunique.ddbs'. 

I have checked there are no duplicate declaration yet I get this error while compiling. Could you tell what could be duplicate?
--------- gradle file ----
apply plugin: 'com.android.library'
apply plugin: 'bintray-release'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

```
defaultConfig {
    minSdkVersion 14
    targetSdkVersion 23
    versionCode 2
    versionName "0.0.4"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services-drive:7.3.0'
    compile 'com.github.athingunique:ddbs:0.0.5'
}

publish {
    userOrg = 'athingunique'
    groupId = 'com.github.athingunique'
    artifactId = 'ddbs'
    publishVersion = '0.0.5'
    description = 'A Google Drive Sync Layer for Android SQLite Database'
    website = 'https://github.com/athingunique/Drive-Database-Sync'
    issueTracker = "${website}/issues"
    repository = "${website}.git"

**Comment by ajaybarvey** [comment]
update: When I commented  "compile 'com.github.athingunique:ddbs:0.0.5' "  in both the gradle files the error was resolved. You can use the updated gradle files below.
Thanks
Ajay
- Working ddbs gradle.build file------------
  apply plugin: 'com.android.library'
  apply plugin: 'bintray-release'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

```
defaultConfig {
    minSdkVersion 14
    targetSdkVersion 23
    versionCode 2
    versionName "0.0.4"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services-drive:7.3.0'
    //compile 'com.github.athingunique:ddbs:0.0.5'
}

publish {
    userOrg = 'athingunique'
    groupId = 'com.github.athingunique'
    artifactId = 'ddbs'
    publishVersion = '0.0.5'
    description = 'A Google Drive Sync Layer for Android SQLite Database'
    website = 'https://github.com/athingunique/Drive-Database-Sync'
    issueTracker = "${website}/issues"
    repository = "${website}.git"
}

---example gradle.build file below------------------------
apply plugin: 'com.android.application'

android {

```
compileSdkVersion 23
buildToolsVersion "23.0.2"
defaultConfig {
    applicationId "com.github.athingunique.ddbs_ex"
    minSdkVersion 14
    targetSdkVersion 23
    versionCode 2
    versionName "0.0.2"
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.jakewharton:butterknife:6.1.0'
    //compile 'com.github.athingunique:ddbs:0.0.5'
    // Include this line to pull from the release repo
    // compile 'com.github.athingunique:ddbs:0.0.4'
    compile project(':ddbs')
}

**Comment by rbtr** [comment]
@ajaybarvey please stop filing issues against the library for problems with your build process.
